#!/bin/bash
source /opt/ros/noetic/setup.bash 
source /home/nuc/catkin_noetic/devel/setup.bash

# Prepare network config for Ouster Lidar
xterm -hold -geometry 80x36+0+0 -e "nmcli con down static" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -geometry 80x36+0+0 -e "nmcli con down static" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -geometry 80x36+0+0 -e "nmcli dev disconnect eno1" & sleep 0.1 #added for flush does not remove existint connection directly
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip addr flush dev eno1" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip addr flush dev eno1" & sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip addr show dev eno1" &  sleep 0.5 
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip addr add 192.168.1.50/24 dev eno1" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip link set eno1 up" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S ip addr show dev eno1" &  sleep 0.5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S dnsmasq -C /dev/null -kd -F 10.5.5.50,10.5.5.100 -i eno1 --bind-dynamic" & sleep 5
xterm -geometry 80x36+0+0 -e "echo 'plutonuc' | sudo -S dnsmasq -C /dev/null -kd -F 192.168.1.50,192.168.1.100 -i eno1 --bind-dynamic" & sleep 5

killall xterm

# Launch EMLID Reach GNSS node
xterm -T "Launch IMU" -geometry 80x15+0+550 -e "roslaunch emlid_reach_ros reach_ros.launch port:=/dev/ttyACM0" & sleep 2

# Launch the vn200 imu
xterm -T "Launch IMU" -geometry 80x15+0+0 -e "roslaunch vectornav vectornav.launch" & sleep 2

# Launch the ouster
xterm -T "Launch Ouster" -geometry 80x15+0+	 -e "roslaunch ouster_ros sensor.launch " & sleep 2

# Launch the livox, which has the rviz
xterm -T "Launch Livox" -geometry 80x15+0+250 -e "roslaunch livox_ros_driver2 livox_lidar_msg.launch bd_list:='3GGDJ5S0010017'" & sleep 2
# Adjust the rviz window
(sleep 3; wmctrl -r 'display_lidar_points.rviz - RViz'  -e '0,1045,361,1369,757') #Adjust the position of rviz
(sleep 3; wmctrl -r 'display_lidar_points.rviz* - RViz' -e '0,1045,361,1369,757') #Adjust the position of rviz

# Launch the realsense camera
xterm -T "Launch D455" -geometry 80x15+0+350 -e "roslaunch realsense2_camera rs_camera_D455_0.launch & roslaunch realsense2_camera rs_camera_D455_1.launch" & sleep 2

# Launch the uwb
xterm -T "Launch UWB" -geometry 80x15+0+450 -e "roslaunch nlink_parser linktrack_atv.launch" & sleep 2

#xterm -T "Dis AE0" -geometry 80x15+0+550 -e "rosrun dynamic_reconfigure dynparam set /rsD455_node0/rgb_camera enable_auto_exposure false" & sleep 2
#xterm -T "Dis AE1" -geometry 80x15+0+550 -e "rosrun dynamic_reconfigure dynparam set /rsD455_node1/rgb_camera enable_auto_exposure false" & sleep 2
#xterm -T "Dis AE2" -geometry 80x15+0+550 -e "rosrun dynamic_reconfigure dynparam set /rsD455_node0/stereo_module enable_auto_exposure false" & sleep 2
#xterm -T "Dis AE3" -geometry 80x15+0+550 -e "rosrun dynamic_reconfigure dynparam set /rsD455_node1/stereo_module enable_auto_exposure false" & sleep 2

#xterm -geometry 80x20+0+590 -e "source ~/dev_ws/devel/setup.bash && roslaunch nlink_parser linktrack_atv.launch" & sleep 2

# Inspect the rates
xterm -T "Subscribed topics" -fa 'Monospace' -fs 10 -geometry 98x08+610+0 -e \
"rostopic hz /vectornav/IMU /os_cloud_node/imu /os_cloud_node/points /livox/lidar /rsD455_node0/imu /rsD455_node0/color/image_raw /rsD455_node1/imu /rsD455_node1/color/image_raw /ltp_tag0/nlf3 /ltp_tag1/nlf3" & sleep 2
(sleep 3; wmctrl -r 'Subscribed topics' -e '0,550,0,680,245') #Adjust the window for subscription status

# Show the cpu
xterm -T "CPU load" -fa 'Monospace' -fs 10 -geometry 98x08+610+0 -e "htop" & sleep 2
(sleep 3; wmctrl -r 'CPU load' -e '0,1240,0,680,245') #Adjust the window for subscription status
